export enum AuthRepositoryEnum {
    ROLE_REPOSITORY = 'ROLE_REPOSITORY',
    USER_REPOSITORY = 'USER_REPOSITORY',
    STATUS_REPOSITORY = 'STATUS_REPOSITORY',
}

export enum ConfigEnum {
    PG_DATA_SOURCE = 'PG_DATA_SOURCE',
}
