export enum UploadFilesRepositoryEnum {
    PERSONAL_DOCUMENTS_REPOSITORY = 'PERSONAL_DOCUMENTS_REPOSITORY',
    INSCRIPTION_DOCUMENTS_REPOSITORY = 'INSCRIPTION_DOCUMENTS_REPOSITORY',
    DEGREE_DOCUMENTS_REPOSITORY = 'DEGREE_DOCUMENTS_REPOSITORY',
    RECORD_REPOSITORY = 'RECORD_REPOSITORY',
    GRADE_ENROLLMENT_REPOSITORY = 'GRADE_ENROLLMENT_REPOSITORY',
    ENROLLMENT_DOC_REPOSITORY = 'ENROLLMENT_DOC_REPOSITORY',
}